import os
import sys
import time
import math
import sqlite3
import datetime
import getpass
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import ListedColormap
from scipy import stats
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.datasets import make_blobs
from textblob import TextBlob
from fpdf import FPDF

# --- LIBRARY TAMPILAN ---
from colorama import init, Fore, Style, Back
from tabulate import tabulate

init(autoreset=True)

# ==========================================
# BAGIAN DATABASE (SQLITE)
# ==========================================
def init_db():
    """Membuat database otomatis jika belum ada"""
    conn = sqlite3.connect('uas_system.db')
    c = conn.cursor()
    # Tabel Log Aktivitas
    c.execute('''CREATE TABLE IF NOT EXISTS activity_log
                 (id INTEGER PRIMARY KEY AUTOINCREMENT,
                  timestamp TEXT,
                  user TEXT,
                  action TEXT)''')
    conn.commit()
    conn.close()

def log_activity(user, action):
    """Menyimpan aktivitas ke database"""
    conn = sqlite3.connect('uas_system.db')
    c = conn.cursor()
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    c.execute("INSERT INTO activity_log (timestamp, user, action) VALUES (?, ?, ?)", (now, user, action))
    conn.commit()
    conn.close()

def view_logs():
    """Melihat histori penggunaan aplikasi"""
    print_header()
    print(f"{Back.MAGENTA}{Fore.WHITE} [ SYSTEM AUDIT LOGS ] {Style.RESET_ALL}\n")
    conn = sqlite3.connect('uas_system.db')
    df = pd.read_sql_query("SELECT * FROM activity_log ORDER BY id DESC LIMIT 10", conn)
    conn.close()
    
    if not df.empty:
        print(tabulate(df, headers='keys', tablefmt='fancy_grid', showindex=False))
    else:
        print(f"{Fore.YELLOW}Belum ada aktivitas terekam.")
    pause()

# ==========================================
# FITUR PDF REPORTING
# ==========================================
def generate_pdf_report(modul_name, result_text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Laporan Hasil Analisis Sistem", ln=1, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt=f"Generated by: Rizqi Ghani | Date: {datetime.datetime.now()}", ln=1, align='C')
    pdf.line(10, 30, 200, 30)
    
    # Content
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt=f"Modul: {modul_name}", ln=1)
    pdf.set_font("Courier", size=11)
    pdf.multi_cell(0, 10, txt=result_text)
    
    # Footer
    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, f'Page {pdf.page_no()}', 0, 0, 'C')
    
    filename = f"Report_{modul_name}_{int(time.time())}.pdf"
    pdf.output(filename)
    print(f"\n{Back.GREEN}{Fore.BLACK} PDF REPORT GENERATED: {filename} {Style.RESET_ALL}")
    time.sleep(1)

# ==========================================
# KONFIGURASI UI
# ==========================================
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def loading_animation(text="Processing", duration=1.0):
    print(f"\n{Fore.YELLOW}{text}", end="")
    for i in range(3):
        time.sleep(0.2)
        sys.stdout.write(".")
        sys.stdout.flush()
    print(f" {Fore.GREEN}[DONE]\n")

def print_header():
    clear_screen()
    print(Fore.CYAN + Style.BRIGHT + "="*85)
    print(Fore.CYAN + r"""
  ____  _         _    ____  _                         __  _____  
 |  _ \(_)_______(_)  / ___|| |__   __ _ _ __ (_)      \ \/ /_ _| 
 | |_) | |_  / __| | | |  _| '_ \ / _` | '_ \| |  ____  \  / | |  
 |  _ <| |/ / (__| | | |_| | | | | (_| | | | | | |____| /  \ | |  
 |_| \_\_/___\___|_|  \____|_| |_|\__,_|_| |_|_|       /_/\_\___| 
                                                                  
    ENTERPRISE DATA SUITE v4.0 - FINAL EXAM EDITION
    """)
    print(Fore.CYAN + "="*85)
    info = [["User", "Rizqi Ghani (Admin)"], ["DB Status", "Connected (SQLite3)"], ["System", "Online"]]
    print(tabulate(info, tablefmt="simple", stralign="center"))
    print("-" * 85)

def pause():
    input(f"\n{Back.CYAN}{Fore.BLACK} ENTER {Style.RESET_ALL} Kembali ke menu...")

# ==========================================
# MODUL BARU: NLP (SENTIMENT ANALYSIS)
# ==========================================
def nlp_sentiment_analysis():
    print_header()
    print(f"{Back.MAGENTA}{Fore.WHITE} [ AI: SENTIMENT ANALYSIS (NLP) ] {Style.RESET_ALL}\n")
    print("Modul ini menggunakan Natural Language Processing untuk mendeteksi emosi teks.")
    print("Contoh: 'Saya sangat senang hari ini' (Positif) atau 'Pelayanan buruk sekali' (Negatif)\n")
    
    text = input(f"{Fore.GREEN}>> Masukkan Kalimat (Inggris/Indo): {Fore.WHITE}")
    
    loading_animation("Menganalisis Bahasa")
    blob = TextBlob(text)
    
    # Translasi otomatis ke Inggris jika perlu (karena TextBlob native Inggris)
    try:
        if blob.detect_language() != 'en':
            blob = blob.translate(to='en')
    except:
        pass # Lanjut saja jika gagal translate (koneksi internet diperlukan untuk translate)

    polarity = blob.sentiment.polarity
    subjectivity = blob.sentiment.subjectivity
    
    if polarity > 0: 
        sentiment = "POSITIF 😊"
        color = Fore.GREEN
    elif polarity < 0: 
        sentiment = "NEGATIF 😡"
        color = Fore.RED
    else: 
        sentiment = "NETRAL 😐"
        color = Fore.YELLOW
        
    hasil = [
        ["Kalimat Input", text],
        ["Sentimen", sentiment],
        ["Skor Polaritas", f"{polarity:.2f} (-1 s/d 1)"],
        ["Subjektivitas", f"{subjectivity:.2f} (Fakta vs Opini)"]
    ]
    
    print(f"\n{color}" + tabulate(hasil, tablefmt="fancy_grid"))
    
    # Log ke database
    log_activity("Admin", f"NLP Analysis: {sentiment}")
    
    if input(f"\n{Fore.YELLOW}Cetak PDF? (y/n): ").lower() == 'y':
        report_text = f"Input: {text}\nResult: {sentiment}\nScore: {polarity}\n\nAnalysis completed by NLP Module."
        generate_pdf_report("Sentiment Analysis", report_text)
    
    pause()

# ==========================================
# MODUL LAMA (DIPERBARUI DENGAN LOG)
# ==========================================
def data_cleaning_demo():
    print_header()
    print(f"{Back.BLUE}{Fore.WHITE} [ DATA CLEANING & EXPORT ] {Style.RESET_ALL}\n")
    data = {'Nama': ['Ali', 'Budi', 'Citra', 'Deni'], 'Nilai': [85, np.nan, 90, np.nan]}
    df = pd.DataFrame(data)
    
    print("Data Awal:\n", df)
    loading_animation("Cleaning Data")
    df['Nilai'] = df['Nilai'].fillna(df['Nilai'].mean())
    print("\nData Bersih:\n", df)
    
    log_activity("Admin", "Performed Data Cleaning")
    pause()

def ml_kmeans_clustering():
    print_header()
    print(f"{Back.BLUE}{Fore.WHITE} [ K-MEANS CLUSTERING ] {Style.RESET_ALL}\n")
    loading_animation("Training AI")
    X, y = make_blobs(n_samples=300, centers=4, cluster_std=0.60)
    kmeans = KMeans(n_clusters=4)
    kmeans.fit(X)
    y_kmeans = kmeans.predict(X)
    
    plt.scatter(X[:, 0], X[:, 1], c=y_kmeans, s=50, cmap='viridis')
    plt.title("K-Means Clustering Result")
    plt.show()
    
    log_activity("Admin", "Ran K-Means Clustering")
    pause()

def login_system():
    clear_screen()
    init_db() # Pastikan DB siap
    print(Fore.GREEN + "=== SECURE ENTERPRISE LOGIN v4.0 ===")
    
    user = input(f"\nUsername: ")
    pwd = input(f"Password: ") # Sederhana agar tidak error di IDE tertentu
    
    if user == "admin" and pwd == "admin123":
        print(f"\n{Back.GREEN}{Fore.BLACK} LOGIN SUKSES {Style.RESET_ALL}")
        log_activity(user, "User Login Success")
        time.sleep(1)
        return True
    else:
        print(f"\n{Back.RED}{Fore.WHITE} LOGIN GAGAL {Style.RESET_ALL}")
        return False

# ==========================================
# MAIN MENU
# ==========================================
def main():
    if login_system():
        while True:
            print_header()
            menu = [
                ["1", "Data Cleaning (Pandas)"],
                ["2", "Sentiment Analysis (NLP AI) [NEW]"],
                ["3", "K-Means Clustering (Machine Learning)"],
                ["4", "System Audit Logs (Database) [NEW]"],
                ["0", "EXIT & SAVE"]
            ]
            print(tabulate(menu, headers=["No", "Modul Enterprise"], tablefmt="rounded_outline"))
            
            choice = input(f"\n{Fore.GREEN}admin@enterprise:~# {Fore.WHITE}")
            
            if choice == '1': data_cleaning_demo()
            elif choice == '2': nlp_sentiment_analysis()
            elif choice == '3': ml_kmeans_clustering()
            elif choice == '4': view_logs()
            elif choice == '0':
                log_activity("Admin", "System Shutdown")
                print(f"\n{Fore.CYAN}System shut down safely.")
                sys.exit()
            else:
                print("Invalid command.")
                time.sleep(1)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Force Close.")
